// Generates placeholder PDF documents into the downloads/ folder.
// Replace these files with the union's real documents whenever available -
// the filenames below are what the site links to.
// Usage: node scripts/generate-pdfs.js
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'downloads');
fs.mkdirSync(OUT, { recursive: true });

function makePdf(lines) {
  const objs = [];
  objs.push('<< /Type /Catalog /Pages 2 0 R >>');
  objs.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
  const content = [
    'BT',
    '/F1 22 Tf',
    '72 720 Td',
    `(${lines.title}) Tj`,
    '/F1 11 Tf',
    '0 -40 Td',
    ...lines.body.map((t, i) => {
      const parts = wrap(t, 92);
      const out = [];
      parts.forEach((p) => {
        out.push(`(${sanitize(p)}) Tj`, '0 -18 Td');
      });
      return out.join('\n');
    }),
    'ET'
  ].join('\n');
  objs.push(
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>'
  );
  objs.push(`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`);
  objs.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');

  let pdf = '%PDF-1.4\n';
  const offsets = [];
  objs.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefStart = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((off) => {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  return pdf;
}

function sanitize(s) {
  return s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function wrap(s, width) {
  const words = s.split(' ');
  const lines = [];
  let cur = '';
  for (const w of words) {
    if ((cur + ' ' + w).trim().length > width) {
      lines.push(cur.trim());
      cur = w;
    } else {
      cur = (cur + ' ' + w).trim();
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

const docs = [
  {
    file: 'UFABWU-Constitution.pdf',
    title: 'UFABWU UNION CONSTITUTION',
    body: [
      'PLACEHOLDER DOCUMENT - generated by the UFABWU website backend.',
      'Replace this file with the official Constitution (LUN 38) PDF.',
      '',
      'This Constitution governs the Delegates Conference, National Executive',
      'Council organ elections, membership rights and obligations, branch',
      'procedures, and the amendment process of the Uganda Farm and Agro-Based',
      "Workers' Union, registered on 29th December 2006 as Labour Union No. 38.",
      '',
      'For the official copy, contact the National Secretariat:',
      '+256 772 518902  |  P.O. Box 34214, Kampala, Uganda.'
    ]
  },
  {
    file: 'Standard-CBA-Template.pdf',
    title: 'MODEL COLLECTIVE BARGAINING AGREEMENT',
    body: [
      'PLACEHOLDER DOCUMENT - generated by the UFABWU website backend.',
      'Replace this file with the official Model CBA template PDF.',
      '',
      'This template Collective Bargaining Agreement is provided for',
      'agricultural enterprises, plantations, and agro-processing units.',
      'It covers recognition, wages, working hours, occupational safety,',
      'grievance procedures, and dispute resolution in line with the',
      'Labour Unions Act No. 7 of 2006.',
      '',
      'For the official template, contact the National Secretariat:',
      '+256 772 518902  |  P.O. Box 34214, Kampala, Uganda.'
    ]
  },
  {
    file: 'OSH-Safety-Guide.pdf',
    title: 'OCCUPATIONAL HEALTH & SAFETY GUIDE',
    body: [
      'PLACEHOLDER DOCUMENT - generated by the UFABWU website backend.',
      'Replace this file with the official OSH Safety Guide PDF.',
      '',
      'This manual covers pesticide handling and spraying, use of personal',
      'protective equipment (PPE), heavy machinery operation, injury',
      'prevention, and emergency response for plantation and farm workers.',
      '',
      'For the official guide, contact the National Secretariat:',
      '+256 772 518902  |  P.O. Box 34214, Kampala, Uganda.'
    ]
  }
];

for (const d of docs) {
  const pdf = makePdf(d);
  fs.writeFileSync(path.join(OUT, d.file), pdf);
  console.log(`Created downloads/${d.file} (${pdf.length} bytes)`);
}
